export const DEFAULT_LOG_RETENTION_DAYS = 30;
export const DEFAULT_LOG_RETENTION_BATCH_SIZE = 5_000;
export const DEFAULT_LOG_RETENTION_MAX_BATCHES = 400;
export const DEFAULT_LOG_RETENTION_MAX_RUN_MS = 3_300_000;

export const MAX_LOG_RETENTION_DAYS = 3_650;
export const MAX_LOG_RETENTION_BATCH_SIZE = 10_000;
export const MAX_LOG_RETENTION_MAX_BATCHES = 10_000;
export const MAX_LOG_RETENTION_MAX_RUN_MS = 3_599_999;

export const LOG_RETENTION_CRON_EXPRESSION = '0 0 * * * *';
export const LOG_RETENTION_JOB_NAME = 'log-retention';
export const LOG_RETENTION_ADVISORY_LOCK_ID = 1_784_876_321;
