import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCanonicalLogsSchema1784905000000
  implements MigrationInterface
{
  name = 'CreateCanonicalLogsSchema1784905000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE EXTENSION IF NOT EXISTS pg_trgm');

    await queryRunner.query(`
      CREATE FUNCTION log_attributes_are_flat_scalars(input jsonb)
      RETURNS boolean
      LANGUAGE sql
      IMMUTABLE
      STRICT
      PARALLEL SAFE
      AS $function$
        SELECT
          jsonb_typeof(input) = 'object'
          AND NOT EXISTS (
            SELECT 1
            FROM jsonb_each(input) AS attribute
            WHERE jsonb_typeof(attribute.value) NOT IN ('string', 'number', 'boolean')
          )
      $function$
    `);

    await queryRunner.query(`
      CREATE TYPE logs_level_enum AS ENUM ('debug', 'info', 'warn', 'error')
    `);

    await queryRunner.query(`
      CREATE TABLE logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        timestamp timestamptz NOT NULL,
        level logs_level_enum NOT NULL,
        service text NOT NULL,
        message text NOT NULL,
        attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT pk_logs PRIMARY KEY (id),
        CONSTRAINT chk_logs_service_non_empty CHECK (char_length(service) > 0),
        CONSTRAINT chk_logs_message_non_empty CHECK (char_length(message) > 0),
        CONSTRAINT chk_logs_attributes_flat_scalars
          CHECK (log_attributes_are_flat_scalars(attributes))
      )
    `);

    await queryRunner.query(`
      CREATE INDEX idx_logs_timestamp_id
      ON logs (timestamp DESC, id DESC)
    `);
    await queryRunner.query(`
      CREATE INDEX idx_logs_service_hash_timestamp_id
      ON logs (md5(service), timestamp DESC, id DESC)
    `);
    await queryRunner.query(`
      CREATE INDEX idx_logs_level_timestamp_id
      ON logs (level, timestamp DESC, id DESC)
    `);
    await queryRunner.query(`
      CREATE INDEX idx_logs_message_trgm
      ON logs USING gin (message gin_trgm_ops)
    `);
    await queryRunner.query(`
      CREATE STATISTICS stats_logs_service_hash_dependency (dependencies)
      ON md5(service), service
      FROM logs
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS logs');
    await queryRunner.query('DROP TYPE IF EXISTS logs_level_enum');
    await queryRunner.query(
      'DROP FUNCTION IF EXISTS log_attributes_are_flat_scalars(jsonb)',
    );
  }
}
